const states: { [state: string]: string } = {
  "Acre": "AC",
  "Alagoas": "AL",
  "Amapa": "AP",
  "Amazonas": "AM",
  "Bahia": "BA",
  "Ceara": "CE",
  "Distrito Federal": "DF",
  "Espírito Santo": "ES",
  "Goias": "GO",
  "Maranhao": "MA",
  "Mato Grosso": "MT",
  "Mato Grosso do Sul": "MS",
  "Minas Gerais": "MG",
  "Para": "PA",
  "Paraiba": "PB",
  "Parana": "PR",
  "Pernambuco": "PE",
  "Piaui": "PI",
  "Rio de Janeiro": "RJ",
  "Rio Grande do Norte": "RN",
  "Rio Grande do Sul": "RS",
  "Rondonia": "RO",
  "Roraima": "RR",
  "Santa Catarina": "SC",
  "Sao Paulo": "SP",
  "Sergipe": "SE",
  "Tocantins": "TO",
  "Aguas calientes": "AGU",
  "Baja California": "BC",
  "Baja California Sur": "BCS",
  "Campeche": "CAM",
  "Chiapas": "CHP",
  "Chihuahua": "CHH",
  "Coahuila": "COA",
  "Colima": "COL",
  "Durango": "DUR",
  "Guanajuato": "GUA",
  "Guerrero": "GRO",
  "Hidalgo": "HID",
  "Jalisco": "JAL",
  "México": "MEX",
  "Michoacán": "MIC",
  "Morelos": "MOR",
  "Nayarit": "NAY",
  "Nuevo León": "NLE",
  "Oaxaca": "OAX",
  "Puebla": "PUE",
  "Querétaro": "QUE",
  "Quintana Roo": "ROO",
  "San Luis Potosí": "SLP",
  "Sinaloa": "SIN",
  "Sonora": "SON",
  "Tabasco": "TAB",
  "Tamaulipas": "TAM",
  "Tlaxcala": "TLA",
  "Veracruz": "VER",
  "Yucatán": "YUC",
  "Zacatecas": "ZAC",
  "Badakhshan": "BDS",
  "Badghis": "BDG",
  "Baghlan": "BGL",
  "Balkh": "BAL",
  "Bamyan": "BAM",
  "Daykundi": "DAY",
  "Farah": "FRA",
  "Faryab": "FYB",
  "Ghazni": "GHA",
  "Ghor": "GHO",
  "Helmand": "HEL",
  "Herat": "HER",
  "Jowzjan": "JOW",
  "Kabul": "KAB",
  "Kandahar": "KAN",
  "Kapisa": "KAP",
  "Khost": "KHO",
  "Kunar": "KNR",
  "Kunduz": "KDZ",
  "Laghman": "LAG",
  "Logar": "LOG",
  "Nangarhar": "NAN",
  "Nimruz": "NIM",
  "Nuristan": "NUR",
  "Paktia": "PIA",
  "Paktika": "PKA",
  "Panjshir": "PAN",
  "Parwan": "PAR",
  "Samangan": "SAM",
  "Sar-e Pol": "SAR",
  "Takhar": "TAK",
  "Urozgan": "URU",
  "Zabul": "ZAB",
  "Adrar": "ADR",
  "Aïn Defla": "ADE",
  "Aïn Témouchent": "ATE",
  "Algiers": "ALG",
  "Annaba": "AAE",
  "Batna": "BAT",
  "Béchar": "BEC",
  "Béjaïa": "BJA",
  "Biskra": "BIS",
  "Blida": "BLI",
  "Bordj Bou Arréridj": "BOA",
  "Bouira": "BOU",
  "Boumerdès": "BMD",
  "Chlef": "CHL",
  "Constantine": "CON",
  "Djelfa": "DJE",
  "El Bayadh": "EBA",
  "El Oued": "EOU",
  "El Tarf": "ETA",
  "Ghardaïa": "GHA",
  "Guelma": "GUE",
  "Illizi": "ILL",
  "Jijel": "JIJ",
  "Khenchela": "KHE",
  "Laghouat": "LAG",
  "M'Sila": "MSI",
  "Mascara": "MAS",
  "Médéa": "MED",
  "Mila": "MIL",
  "Mostaganem": "MOS",
  "Naama": "NAA",
  "Oran": "ORA",
  "Ouargla": "OUA",
  "Oum El Bouaghi": "OEB",
  "Relizane": "REL",
  "Saida": "SAI",
  "Sétif": "SET",
  "Sidi Bel Abbès": "SBA",
  "Skikda": "SKI",
  "Souk Ahras": "SAH",
  "Tamanghasset": "TAM",
  "Tébessa": "TEB",
  "Tiaret": "TIA",
  "Tindouf": "TIN",
  "Tipaza": "TIP",
  "Tissemsilt": "TIS",
  "Tizi Ouzou": "TIZ",
  "Tlemcen": "TLE",
  "Andorra la Vella": "07",
  "Canillo": "02",
  "Encamp": "03",
  "Escaldes-Engordany": "08",
  "La Massana": "04",
  "Ordino": "05",
  "Sant Julià de Lòria": "06",
  "Bengo": "BGO",
  "Benguela": "BGU",
  "Bié": "BIE",
  "Cabinda": "CAB",
  "Cuando Cubango": "CCU",
  "Cuanza Norte": "CNO",
  "Cuanza Sul": "CUS",
  "Huambo": "HUA",
  "Huíla": "HUI",
  "Luanda": "LUA",
  "Lunda Norte": "LNO",
  "Lunda Sul": "LSU",
  "Malanje": "MAL",
  "Moxico": "MOX",
  "Namibe": "NAM",
  "Uíge": "UIG",
  "Zaire": "ZAI",
  "Anguilla": "AI",
  "Antigua and Barbuda": "01",
  "Barbuda": "10",
  "Redonda": "11",
  "Saint George": "03",
  "Saint John": "04",
  "Saint Mary": "05",
  "Saint Paul": "06",
  "Saint Peter": "07",
  "Saint Philip": "08",
  "Argentina": "AR",
  "Buenos Aires": "BUE",
  "Catamarca": "AR-K",
  "Chaco": "AR-H",
  "Chubut": "AR-U",
  "Córdoba": "CB",
  "Corrientes": "CTES",
  "Entre Ríos": "ER",
  "Formosa": "FOR",
  "Jujuy": "JU",
  "La Pampa": "LP",
  "La Rioja": "LR",
  "Mendoza": "MZA",
  "Misiones": "MI",
  "Neuquén": "NQ",
  "Río Negro": "RN",
  "Salta": "SA",
  "San Juan": "SJ",
  "San Luis": "SL",
  "Santa Cruz": "SC",
  "Santa Fe": "SF",
  "Santiago del Estero": "SE",
  "Tierra del Fuego": "TF",
  "Tucumán": "TUC",
  "Armenia": "AM",
  "Artsakh": "11",
  "Aragatsotn Province": "AG",
  "Ararat Province": "AR",
  "Armavir Province": "AV",
  "Gegharkunik Province": "GR",
  "Kotayk Province": "KT",
  "Lori Province": "LO",
  "Shirak Province": "SH",
  "Syunik Province": "SU",
  "Tavush Province": "TV",
  "Vayots Dzor Province": "VD",
  "Yerevan": "ER",
  "Aruba": "AW",
  "Australian Capital Territory": "ACT",
  "New South Wales": "NSW",
  "Northern Territory": "NT",
  "Queensland": "QLD",
  "South Australia": "SA",
  "Tasmania": "TAS",
  "Victoria": "VIC",
  "Western Australia": "WA",
  "Austria": "AT",
  "Burgenland": "B",
  "Carinthia": "K",
  "Lower Austria": "NÖ",
  "Upper Austria": "OÖ",
  "Salzburg": "S",
  "Styria": "ST",
  "Tyrol": "T",
  "Vorarlberg": "V",
  "Vienna": "W",
  "Azerbaijan": "AZ",
  "Absheron District": "ABS",
  "Agdam District": "AGM",
  "Agdash District": "AGS",
  "Agstafa District": "AGA",
  "Aghjabadi District": "AGC",
  "Agsu District": "AGU",
  "Astara District": "AST",
  "Babek District": "BAB",
  "Baku": "BAK",
  "Balakan District": "BAL",
  "Barda District": "BAR",
  "Beylagan District": "BEY",
  "Bilasuvar District": "BIL",
  "Dashkasan District": "DAS",
  "Fuzuli District": "FUZ",
  "Ganja": "GA",
  "Gobustan District": "QOB",
  "Goranboy District": "GOR",
  "Goychay District": "GOY",
  "Goygol District": "GYG",
  "Hajigabul District": "HAC",
  "Imishli District": "IMI",
  "Ismailli District": "ISM",
  "Jabrayil District": "CAB",
  "Jalilabad District": "CAL",
  "Julfa District": "CUL",
  "Khachmaz District": "XAC",
  "Khizi District": "XIZ",
  "Khojaly District": "CUL",
  "Kurdamir District": "KUR",
  "Lachin District": "LAC",
  "Lankaran District": "LAN",
  "Lankaran": "LA",
  "Lerik District": "LER",
  "Masally District": "MAS",
  "Mingachevir": "MI",
  "Naftalan": "NA",
  "Nakhchivan Autonomous Republic": "NX",
  "Neftchala District": "NEF",
  "Oghuz District": "OGU",
  "Qabala District": "QAB",
  "Qakh District": "QAX",
  "Qazakh District": "QAZ",
  "Quba District": "QBA",
  "Qubadli District": "QBI",
  "Qusar District": "QUS",
  "Saatly District": "SAT",
  "Sabirabad District": "SAB",
  "Shabran District": "SBN",
  "Shaki": "SA",
  "Shaki District": "SAK",
  "Shamakhi District": "SMI",
  "Shamkir District": "SKR",
  "Shirvan": "SIR",
  "Shusha District": "SUS",
  "Siazan District": "SIA",
  "Sumqayit": "SM",
  "Tartar District": "TAR",
  "Tovuz District": "TOV",
  "Ujar District": "UCA",
  "Yardymli District": "YAR",
  "Yevlakh District": "YEV",
  "Zangilan District": "ZAN",
  "Zaqatala District": "ZAQ",
  "Zardab District": "ZAR",
  "Bahamas": "BS",
  "Acklins": "01",
  "Berry Islands": "02",
  "Bimini": "03",
  "Black Point": "04",
  "Cat Island": "05",
  "Central Abaco": "06",
  "Central Andros": "07",
  "Central Eleuthera": "08",
  "City of Freeport": "09",
  "Crooked Island and Long Cay": "10",
  "East Grand Bahama": "11",
  "Exuma": "12",
  "Grand Cay": "13",
  "Harbour Island": "14",
  "Inagua": "15",
  "Long Island": "16",
  "Mangrove Cay": "17",
  "Mayaguana": "18",
  "Moore's Island": "19",
  "North Abaco": "20",
  "North Andros": "21",
  "North Eleuthera": "22",
  "Ragged Island": "23",
  "Rum Cay": "24",
  "San Salvador and Rum Cay": "13",
  "San Salvador Island": "25",
  "South Abaco": "26",
  "South Andros": "27",
  "South Eleuthera": "28",
  "Spanish Wells": "29",
  "West Grand Bahama": "30",
  "Bahrain": "BH",
  "Al-Janūbīyah": "14",
  "Al-Manāmah": "13",
  "Al-Muḥarraq": "15",
  "Al-Wusṭā": "16",
  "Ash-Shamālīyah": "17",
  "Bujumbura Mairie Province": "BM",
  "Bubanza Province": "BB",
  "Bururi Province": "BR",
  "Cankuzo Province": "CA",
  "Cibitoke Province": "CI",
  "Gitega Province": "GI",
  "Karuzi Province": "KR",
  "Kayanza Province": "KY",
  "Kirundo Province": "KI",
  "Makamba Province": "MA",
  "Muramvya Province": "MU",
  "Muyinga Province": "MY",
  "Mwaro Province": "MW",
  "Ngozi Province": "NG",
  "Rumonge Province": "RM",
  "Rutana Province": "RT",
  "Ruyigi Province": "RY",
  "Benin": "BJ",
  "Alibori Department": "AL",
  "Atakora Department": "AK",
  "Atlantique Department": "AQ",
  "Borgou Department": "BO",
  "Collines Department": "CO",
  "Donga Department": "DO",
  "Kouffo Department": "KO",
  "Littoral Department": "LI",
  "Mono Department": "MO",
  "Ouémé Department": "OU",
  "Plateau Department": "PL",
  "Zou Department": "ZO",
  "Bhutan": "BT",
  "Bumthang District": "33",
  "Chukha District": "12",
  "Dagana District": "22",
  "Gasa District": "GA",
  "Haa District": "13",
  "Lhuntse District": "44",
  "Mongar District": "42",
  "Paro District": "11",
  "Pemagatshel District": "43",
  "Punakha District": "23",
  "Samdrup Jongkhar District": "45",
  "Samtse District": "14",
  "Sarpang District": "31",
  "Thimphu District": "15",
  "Trashigang District": "41",
  "Trongsa District": "32",
  "Tsirang District": "21",
  "Wangdue Phodrang District": "24",
  "Zhemgang District": "34",
  "Bolivia": "BO",
  "Beni Department": "B",
  "Chuquisaca Department": "H",
  "Cochabamba Department": "C",
  "La Paz Department": "L",
  "Oruro Department": "O",
  "Pando Department": "N",
  "Potosí Department": "P",
  "Santa Cruz Department": "S",
  "Tarija Department": "T",
  "Bosnia and Herzegovina": "BA",
  "Bosnian-Podrinje Canton Goražde": "BPG",
  "Brčko District": "BRC",
  "Central Bosnia Canton": "SC",
  "Canton 10": "10",
  "Herzegovina-Neretva Canton": "HN",
  "Posavina Canton": "PU",
  "Sarajevo Canton": "09",
  "Tuzla Canton": "TZ",
  "Una-Sana Canton": "US",
  "West Herzegovina Canton": "WZH",
  "Zenica-Doboj Canton": "ZDC",
  "Botswana": "BW",
  "Central District": "CE",
  "Ghanzi District": "GH",
  "Kgalagadi District": "KG",
  "Kgatleng District": "KL",
  "Kweneng District": "KW",
  "North-East District": "NE",
  "North-West District": "NW",
  "South-East District": "SE",
  "Southern District": "SO",
}

export default states;